services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1003
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - /opt/radarr:/config
      - /mnt/plex/Movies:/movies
      - /mnt/plex/synced_downloads:/downloads
    ports:
      - 7878:8989
    restart: unless-stopped
