services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=sonarr
      - PGID=plex
      - TZ=Etc/UTC
    volumes:
      - /opt/sonarr:/config
      - /mnt/plex/TV_Shows:/tv
      - /mnt/plex/synced_downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped