services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1005
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - /opt/bazarr/config:/config
      - /mnt/plex/Movies:/movies #optional
      - /mnt/plex/TV_Shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
